[[main]]
name = "Home"
url = ""
weight = 10

[[main]]
identifier = "docs"
name = "Docs"
url = "docs"
weight = 50 

[[main]]
identifier = "timeline"
name = "Timeline"
url = "timeline"
weight = 60 

[[main]]
identifier = "support"
name = "Support"
url = "support"
weight = 70 